#!/usr/bin/env php
<?php

use EasySwoole\EasySwoole\Command\CommandContainer;
use EasySwoole\EasySwoole\Command\CommandRunner;
use EasySwoole\EasySwoole\Command\DefaultCommand\Help;
use EasySwoole\EasySwoole\Config;

defined('IN_PHAR') or define('IN_PHAR', boolval(\Phar::running(false)));
defined('RUNNING_ROOT') or define('RUNNING_ROOT', realpath(getcwd()));
defined('EASYSWOOLE_ROOT') or define('EASYSWOOLE_ROOT', IN_PHAR ? \Phar::running() : realpath(getcwd()));

$file = EASYSWOOLE_ROOT.'/vendor/autoload.php';
if (file_exists($file)) {
    require $file;
}else{
    die("include composer autoload.php fail\n");
}

if(file_exists(EASYSWOOLE_ROOT.'/bootstrap.php')){
    require_once EASYSWOOLE_ROOT.'/bootstrap.php';
}

$args = $argv;
//trim first command
array_shift($args);
//自定义命令行
$customConsole = [
    \Console\UserConsole::class,
    \Console\CommandMakeCommand::class,
];
if(!empty($customConsole)) {
    foreach($customConsole as $value) {
        CommandContainer::getInstance()->set(new $value());
    }
}

$ret = CommandRunner::getInstance()->run($args);
if(!empty($ret)){
    echo $ret."\n";
}
